### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [EdinCuturic/awin-conversion-tag-google-tag-manager#1]
https://github.com/EdinCuturic/awin-conversion-tag-google-tag-manager/blob/4f4fa4e89d426ccad695477b4e5b4b64937f2e87/template.tpl#L140

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [[EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri)](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [[EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent)](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by EdinCuturic** [comment]
@philpott thank you. I added the encoding https://github.com/EdinCuturic/awin-conversion-tag-google-tag-manager/commit/3197d0a6aedc21540035836c5da3b78edffce812
