### ISSUE TITLE
Add ability to specify AWIN.Tracking.Sale.click attribute

### ISSUE THREAD

**Issue by PatrickBauer** [EdinCuturic/awin-conversion-tag-google-tag-manager#2]
The master tag uses the `AWIN.Tracking.Sale.click` attribute to allow the Awin event to override the cks parameter. Right now we're not able to set its value using this tag.

**Comment by EdinCuturic** [comment]
@PatrickBauer if you would like to override the awc value then please use the Custom HTML tag.

**Comment by PatrickBauer** [comment]
I simply changed the script part of the tag template and used the custom arrays to send a click attribute 👍
